### ISSUE TITLE
Can you add automatic build of sdl2-compat?

### ISSUE THREAD

**Issue by Curculigo** [mmozeiko/build-sdl3#4]
The program I use still stuck with SDL2 and the sdl2-compat project is very handy:

https://github.com/libsdl-org/sdl2-compat

I have tried to build sdl2-compat against your automatic sdl3 binary build and it turned out to be very straight forward.

**Comment by mmozeiko** [comment]
Good suggestion. I'll add it.

**Comment by mmozeiko** [comment]
Now builds have SDL2 compat library included.

**Comment by 2vidb51h** [comment]
sdl2-compat now provides binary builds:

https://github.com/libsdl-org/sdl2-compat/releases
